Updating to Naut CSS
developersIndia/stylesheet pull request #3
Opened 2024-04-14 21:01 UTC by Linear-Array

Moving to Naut for easier maintenance and accessibility. Put logo as sidebarimg and banner has headerimg. Sidebar markdown code is in sidebar.md

2024-04-15 05:10 UTC, LinearArray commented
Also just clarifying banners needs to be uploaded as `headerimg` and logo needs to be uploaded as `sidebarimg` in the stylesheet. 

Sidebar markdown code should be pasted in `subreddit settings > sidebar`.

2024-04-15 09:19 UTC, Prakhargarg-2010196 commented
@Linear-Array Can you post the main link from where you are referring naut css from

2024-04-21 07:05 UTC, Bhupesh-V requested changes
Update the old sidebar, added 2 comments for review

2024-04-21 07:05 UTC, Bhupesh-V commented on src/main.css
> +	background-image: url(%%icons8-twitter-40%%);
Can we align the name of the file with the image name here?

2024-04-21 07:05 UTC, Bhupesh-V commented on src/main.css
> +	background-image: url(%%rsz-discord-logo-300x300%%);
Can we align the name of the file with the image name here?

2024-04-21 07:51 UTC, LinearArray commented on src/main.css
> +	background-image: url(%%rsz-discord-logo-300x300%%);
You'll need to set a custom image name when upload it.

2024-04-22 07:50 UTC, Bhupesh-V requested changes

2024-04-22 07:50 UTC, Bhupesh-V commented on src/main.css
> +    background: url(%%spritesheet%%) -48px -32px no-repeat;
What is spritesheet image? Please add that in PR

2024-04-22 09:50 UTC, LinearArray commented
Done, added.

2024-04-22 14:05 UTC, Bhupesh-V requested changes

2024-04-22 14:05 UTC, Bhupesh-V commented on src/main.css
> +    background: transparent url(%%noresults%%) no-repeat 50% 50%;
Missing image

2024-04-22 14:05 UTC, Bhupesh-V commented on src/main.css
> +    background: url(%%commentboxbg%%) no-repeat 50% 50%;
missing image

2024-04-22 14:05 UTC, Bhupesh-V commented on src/main.css
> +    background: url(%%footer%%) 50% 0 / cover no-repeat;
missing image

2024-04-24 19:54 UTC, LinearArray commented
done

2024-04-25 09:43 UTC, merged